### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by Nal44** [hanjinliu/napari-macrokit#1]
Hi,

I installed the napari macrokit(thank you for the plugin !) .

then typed in the console:
from napari_macrokit import get_macro

macro = get_macro("my-plugin-specifier")  # get macro object

@macro.magicgui

but it stays such as : 
@macro.magicgui
...:

then nothing writes in the tab when using my plugin ?

Did I miss a step ?

Thanks

**Comment by hanjinliu** [comment]
From `Plugins > napari-macrokit` you can open a macro widget. The specifier will be shown as a tab in the widget. The text of the widget is updated whenever the macro object is updated.

Could you please clarify in which step you think you have a problem? Following simple example code may help you.

```python
from napari_macrokit import get_macro

macro = get_macro("new")
@macro.magicgui
def add(a: int, b: int):
    print(a,b)
add.show()
```

**Comment by Nal44** [comment]
Hi,
my goal is to use your plugin to record live all steps I am doing with other plugins, but after typing : 
@macro.magicgui
then nothing appends when I click or do something with a plugin , I was expecting that it will record live all steps ? 

I don't want to make function , but rather record live as you show in the GIF, so can I do that and how ?

Thanks a lot,

**Comment by hanjinliu** [comment]
Is all the functions in the "other plugins" decorated with `@macro.magicgui`? `@macro.magicgui` is simply a decorator that converts a normal function into a macro recordable one. It does not do any "magical" stuffs that turn functions in other plugins into recordable ones. In my GIF example, all the functions that were called during the demonstration is decorated with `@macro.magicgui`.

**Comment by Nal44** [comment]
I see ok, hence no it won't work for my needs,
thanks anyway ;D
